services:
  app:
    build: .
    container_name: bioapp-web
    image: bioapp:0.0.1
    env_file:
      - .env
    environment:
      RAILS_ENV: production
      BUNDLE_DEPLOYMENT: "1"
      BUNDLE_WITHOUT: development
      RAILS_MASTER_KEY: "14a83b28bd82020d8767214b51bb252f"
      DATABASE_URL: postgres://postgres:password@db:5432/bioapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/rails
    restart: always

  db:
    image: postgres:15
    container_name: bioapp-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bioapp
    restart: always

  nginx:
    image: nginx:latest
    container_name: bioapp-nginx
    depends_on:
      - app
    ports:
      - "81:81"
      - "443:443"
    restart: always
