version: '3.9'

services:
  app:
    build: .
    container_name: bioapp-web
    environment:
      RAILS_ENV: production
      BUNDLE_DEPLOYMENT: "1"
      BUNDLE_WITHOUT: development
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}  # Defina essa variável no .env
      DATABASE_URL: postgres://postgres:password@db:5432/bioapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/rails
    restart: always

  db:
    image: postgres:15
    container_name: bioapp-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bioapp
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  nginx:
    image: nginx:latest
    container_name: bioapp-nginx
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"
    restart: always