# fly.toml app configuration file generated for bioapp-gh0dpw on 2025-03-18T02:36:04Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bioapp-gh0dpw'
primary_region = 'gru'
console_command = '/rails/bin/rails console'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
